In [2]:
# Importing the most important library numpy
# Numpy is preffered over python lists since most of its implementations are faster (the functions are tied closer with hardware)
import numpy as np

### Run the following to grasp the basics of numpy

In [4]:
# 1D array
arr1=np.array([1,2,3])
print("arr1")
arr1

arr1


array([1, 2, 3])

In [5]:
# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [6]:
# Array of zeros
zeros = np.zeros((2,3))
print("zeros array")
zeros

zeros array


array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# array of ones
ones = np.ones((5,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
# Array with a range of values, start, end , interval
range_arr = np.arange(0, 100, 9)
print("Range Array:", range_arr)

Range Array: [ 0  9 18 27 36 45 54 63 72 81 90 99]


In [15]:
# array with linear space
lineararr=np.linspace(0,100,9)
lineararr


array([  0. ,  12.5,  25. ,  37.5,  50. ,  62.5,  75. ,  87.5, 100. ])

In [24]:
# Random array
randomarr=np.random.rand(3,3,3)
randomarr


array([[[0.28916513, 0.58470204, 0.10055163],
        [0.30642463, 0.61079404, 0.39025375],
        [0.85641223, 0.59244174, 0.44874361]],

       [[0.39642131, 0.27423663, 0.11718125],
        [0.36487958, 0.69992084, 0.93072126],
        [0.09177899, 0.17377457, 0.12227031]],

       [[0.4188973 , 0.46751449, 0.97574291],
        [0.85496137, 0.23436508, 0.85278314],
        [0.8583253 , 0.16583871, 0.28294997]]])

In [31]:
# In a numpy array, all the elements must be homogenous (of the same data type)
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)  # Dimensions
print("Size:", arr.size)  # Total number of elements
print("Data Type:", arr.dtype)  # Type of elements
print("Number of Dimensions:", arr.ndim)  # Number of dimensions

print(randomarr.size)

Shape: (2, 3)
Size: 6
Data Type: int64
Number of Dimensions: 2
27


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Accessing elements
print("Element at [0, 1]:", arr[0, 1])  # Row 0, Column 1

# Slicing
print("First row:", arr[0, :])  # All columns of the first row
print("First column:", arr[:, 0])  # All rows of the first column
print("Subarray:\n", arr[0:2, 1:3])  # Rows 0-1 and Columns 1-2

Element at [0, 1]: 2
First row: [1 2 3]
First column: [1 4]
Subarray:
 [[2 3]
 [5 6]]


In [5]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise operations
print("Addition:", arr1 + arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr2 / arr1)

# Broadcasting
scalar = 2
print("Multiply by scalar:", arr1 * scalar)

# Mathematical functions
print("Square root:", np.sqrt(arr1))
print("Exponential:", np.exp(arr1))

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Division: [4.  2.5 2. ]
Multiply by scalar: [2 4 6]
Square root: [1.         1.41421356 1.73205081]
Exponential: [ 2.71828183  7.3890561  20.08553692]


In [44]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Reshape
reshaped = arr.reshape((6,1))
print("Reshaped Array:\n", reshaped)


print("original arr\n",  arr)
# Transpose
transposed = arr.T
print("Transposed Array:\n", transposed)

print("multiplying with reshaped transpose")
print(arr*((arr.T).reshape(arr.shape)))

Reshaped Array:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
original arr
 [[1 2 3]
 [4 5 6]]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]
multiplying with reshaped transpose
[[ 1  8  6]
 [20 15 36]]


In [48]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stacking
stacked = np.vstack((arr1, arr2))  # Vertical stack
print("Stacked Vertically:\n", stacked)

hstacked = np.hstack((arr1, arr2))  # Horizontal stack
print("Stacked Horizontally:", hstacked)

# Splitting
split = np.split(arr2, 3)  # Split into 3 parts
print("Split Array:", split)

Stacked Vertically:
 [[1 2 3]
 [4 5 6]]
Stacked Horizontally: [1 2 3 4 5 6]
Split Array: [array([4]), array([5]), array([6])]


In [50]:
arr = np.array([4, 2, 3, 4, 5, 6])

# Boolean indexing
even = arr[arr % 2 == 0]
print("Even Numbers:", even)
# Masking is a common technique used
print("Masking:", arr % 2 == 0)

# Filtering
filtered = arr[arr > 3]
print("Numbers greater than 3:", filtered)

Even Numbers: [4 2 4 6]
Masking: [ True  True False  True False  True]
Numbers greater than 3: [4 4 5 6]


In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))
print("Standard Deviation:", np.std(arr))

Sum: 21
Mean: 3.5
Maximum: 6
Minimum: 1
Standard Deviation: 1.707825127659933
